// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsLFfpQz_glzLhRUOCF5mXov46_GbLxcQ',
    appId: '1:898147168739:web:0538507419752bd751b0d6',
    messagingSenderId: '898147168739',
    projectId: 'chatapp-9f614',
    authDomain: 'chatapp-9f614.firebaseapp.com',
    storageBucket: 'chatapp-9f614.appspot.com',
    measurementId: 'G-KPX05B7T50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATzv3-aeiD_w44iq4c1GRFiLDbDYofJMo',
    appId: '1:898147168739:android:b6f20106eeeda3fb51b0d6',
    messagingSenderId: '898147168739',
    projectId: 'chatapp-9f614',
    storageBucket: 'chatapp-9f614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzdV1qn5-ZD6E36e4G3iw1ecHfyNNUBCY',
    appId: '1:898147168739:ios:670de308fdc2059651b0d6',
    messagingSenderId: '898147168739',
    projectId: 'chatapp-9f614',
    storageBucket: 'chatapp-9f614.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzdV1qn5-ZD6E36e4G3iw1ecHfyNNUBCY',
    appId: '1:898147168739:ios:670de308fdc2059651b0d6',
    messagingSenderId: '898147168739',
    projectId: 'chatapp-9f614',
    storageBucket: 'chatapp-9f614.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsLFfpQz_glzLhRUOCF5mXov46_GbLxcQ',
    appId: '1:898147168739:web:30a7d721563b006f51b0d6',
    messagingSenderId: '898147168739',
    projectId: 'chatapp-9f614',
    authDomain: 'chatapp-9f614.firebaseapp.com',
    storageBucket: 'chatapp-9f614.appspot.com',
    measurementId: 'G-6E964TP74M',
  );
}
